name: taglib_dart
description: Pure Dart reimplementation of TagLib
version: 1.0.0
repository: https://github.com/MCredbear/taglib_dart

environment:
  sdk: ^3.7.0-267.0.dev

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
